stages:
- checks
- test
- deploy

pre-commit-check:
  stage: checks
  image: python:3.10-bullseye
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip install pre-commit
    - pre-commit run --all-files

.test:
  before_script:
    - apt-get update
    - apt-get install redis-server -y
    - redis-server --daemonize yes
    - python -V
    - pip install tox

test-38-django40:
  extends: .test
  image: python:3.8-bullseye
  script:
  - tox -e py38-django40
  - bash <(curl -s https://codecov.io/bash)

test-39-django40:
  extends: .test
  image: python:3.9-bullseye
  script:
  - tox -e py39-django40
  - bash <(curl -s https://codecov.io/bash)

test-310-django40:
  extends: .test
  image: python:3.10-bullseye
  script:
  - tox -e py310-django40
  - bash <(curl -s https://codecov.io/bash)

test-311-django40:
  extends: .test
  image: python:3.11-bullseye
  script:
  - tox -e py311-django40
  - bash <(curl -s https://codecov.io/bash)

test-core:
  extends: .test
  image: python:3.10-bullseye
  script:
  - tox -e core

test-docs:
  stage: test
  image: python:3.10-bullseye
  before_script:
  - pip install tox
  script:
    - tox -e docs

deploy-pypi:
  stage: deploy
  image: python:3.10-bullseye

  before_script:
    - pip install build twine

  script:
    - python -m build
    - twine upload dist/*

  only:
    - tags
