stages:
- test
- deploy

before_script:
- apt-get update
- apt-get install redis-server -y
- redis-server --daemonize yes
- python -V
- pip install tox

test-3.6:
  image: python:3.6-buster
  script:  
  - tox -e py36

test-3.7:
  image: python:3.7-buster
  script:  
  - tox -e py37

test-3.8:
  image: python:3.8-buster
  script:  
  - tox -e py38

test-linter:
  image: python:3.8-buster
  script:  
  - tox -e linter

deploy-pypi:
  stage: deploy
  image: python:3.7-buster

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  only:
    - tags
