codecov:
  require_ci_to_pass: yes

coverage:
  status:
    patch:
      default:
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
