# Generated by Django 2.2.5 on 2019-11-20 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(401, 'MoonminingAutomaticFracture'), (402, 'MoonminingExtractionCancelled'), (403, 'MoonminingExtractionFinished'), (404, 'MoonminingExtractionStarted'), (405, 'MoonminingLaserFired'), (501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower'), (513, 'OwnershipTransferred')]),
        ),
        migrations.CreateModel(
            name='EveMoon',
            fields=[
                ('id', models.IntegerField(help_text='Eve Online item ID', primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.FloatField(blank=True, default=None, help_text='x position of the structure in the solar system', null=True)),
                ('position_y', models.FloatField(blank=True, default=None, help_text='y position of the structure in the solar system', null=True)),
                ('position_z', models.FloatField(blank=True, default=None, help_text='z position of the structure in the solar system', null=True)),
                ('eve_solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.EveSolarSystem')),
            ],
        ),
    ]
