# Generated by Django 2.2.5 on 2019-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower'), (512, 'StructuresReinforcementChanged'), (513, 'OwnershipTransferred')]),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(help_text='URL of this webhook, e.g. https://discordapp.com/api/webhooks/123456/abcdef', max_length=255, unique=True),
        ),
    ]
