# Generated by Django 2.2.5 on 2019-11-20 01:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0002_auto_20191120_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='webhook',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this profile', max_length=255)),
                ('notification_types', multiselectfield.db.fields.MultiSelectField(choices=[(401, 'MoonminingAutomaticFracture'), (402, 'MoonminingExtractionCancelled'), (403, 'MoonminingExtractionFinished'), (404, 'MoonminingExtractionStarted'), (405, 'MoonminingLaserFired'), (501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower'), (513, 'OwnershipTransferred')], max_length=67)),
                ('is_active', models.BooleanField(default=True, help_text='whether notifications are sent with this profile')),
                ('owner', models.ForeignKey(help_text='Corporation that owns the structure', on_delete=django.db.models.deletion.CASCADE, to='structures.Owner')),
                ('webhook', models.ForeignKey(blank=True, default=None, help_text='Webhook used for sending structure notifications', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='structures.Webhook')),
            ],
        ),
    ]
