# Generated by Django 2.2.5 on 2019-11-20 01:31

from django.db import migrations, models
import multiselectfield.db.fields
import structures.models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0003_auto_20191120_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(401, 'MoonminingAutomaticFracture'), (402, 'MoonminingExtractionCancelled'), (403, 'MoonminingExtractionFinished'), (404, 'MoonminingExtractionStarted'), (405, 'MoonminingLaserFired'), (513, 'OwnershipTransferred'), (501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='notification_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(401, 'MoonminingAutomaticFracture'), (402, 'MoonminingExtractionCancelled'), (403, 'MoonminingExtractionFinished'), (404, 'MoonminingExtractionStarted'), (405, 'MoonminingLaserFired'), (513, 'OwnershipTransferred'), (501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower')], default=structures.models.get_default_notification_types, max_length=67),
        ),
    ]
