# Generated by Django 2.2.5 on 2019-11-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0004_auto_20191120_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='is_default',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_default',
            field=models.BooleanField(default=False, help_text='whether this profile is automatically added as default profile for all newly added owners'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='Name of this profile', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='webhook',
            field=models.ForeignKey(blank=True, default=None, help_text='Notifications are sent to this webhook', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='structures.Webhook'),
        ),
    ]
