# Generated by Django 2.2.5 on 2019-11-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0004_webhook_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='is_default',
            field=models.BooleanField(default=False, help_text='whether this webhook is automatically set as default webhook for all newly added owners'),
        ),
    ]
