# Generated by Django 2.2.5 on 2019-11-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0005_auto_20191120_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_default',
        ),
    ]
