# Generated by Django 2.2.5 on 2019-11-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0006_auto_20191118_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='profile_id',
        ),
    ]
