# Generated by Django 2.2.5 on 2019-11-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0007_remove_structure_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=None, help_text='date this structure was last updated from the EVE server', null=True),
        ),
    ]
