# Generated by Django 2.2.5 on 2019-11-18 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0008_auto_20191118_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationentity',
            old_name='entity_type',
            new_name='category',
        ),
    ]
