# Generated by Django 2.2.11 on 2020-03-09 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0008_auto_20200209_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecategory',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evecategory',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='eveconstellation',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eveconstellation',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evegroup',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evegroup',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evemoon',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evemoon',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evemoon',
            name='position_x',
            field=models.FloatField(blank=True, default=None, help_text='x position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='evemoon',
            name='position_y',
            field=models.FloatField(blank=True, default=None, help_text='y position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='evemoon',
            name='position_z',
            field=models.FloatField(blank=True, default=None, help_text='z position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='eveplanet',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eveplanet',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='eveplanet',
            name='position_x',
            field=models.FloatField(blank=True, default=None, help_text='x position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='eveplanet',
            name='position_y',
            field=models.FloatField(blank=True, default=None, help_text='y position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='eveplanet',
            name='position_z',
            field=models.FloatField(blank=True, default=None, help_text='z position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='everegion',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='everegion',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evesolarsystem',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evesolarsystem',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='id',
            field=models.PositiveIntegerField(help_text='Eve Online ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evetype',
            name='name',
            field=models.CharField(help_text='Eve Online name', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(blank=True, default=None, help_text='True when this notification has read in the eve client', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.TextField(blank=True, default=None, help_text='Notification details in YAML', null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='position_x',
            field=models.FloatField(blank=True, default=None, help_text='x position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='position_y',
            field=models.FloatField(blank=True, default=None, help_text='y position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='position_z',
            field=models.FloatField(blank=True, default=None, help_text='z position in the solar system', null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='reinforce_weekday',
            field=models.IntegerField(blank=True, default=None, help_text='(no longer used)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='structuretag',
            name='is_default',
            field=models.BooleanField(default=False, help_text='if true this tag will automatically be added to new structures'),
        ),
    ]
