# Generated by Django 2.2.9 on 2020-02-04 19:07

from django.db import migrations, models
import multiselectfield.db.fields
import structures.models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0008_auto_20200204_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(401, 'MoonminingAutomaticFracture'), (402, 'MoonminingExtractionCancelled'), (403, 'MoonminingExtractionFinished'), (404, 'MoonminingExtractionStarted'), (405, 'MoonminingLaserFired'), (513, 'OwnershipTransferred'), (501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower'), (601, 'OrbitalAttacked'), (602, 'OrbitalReinforced'), (701, 'TowerAlertMsg'), (702, 'TowerResourceAlertMsg'), (801, 'EntosisCaptureStarted'), (802, 'SovCommandNodeEventStarted'), (803, 'SovAllClaimAquiredMsg'), (804, 'SovStructureReinforced'), (805, 'SovStructureDestroyed')]),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='notification_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(401, 'MoonminingAutomaticFracture'), (402, 'MoonminingExtractionCancelled'), (403, 'MoonminingExtractionFinished'), (404, 'MoonminingExtractionStarted'), (405, 'MoonminingLaserFired'), (513, 'OwnershipTransferred'), (501, 'StructureAnchoring'), (502, 'StructureDestroyed'), (503, 'StructureFuelAlert'), (504, 'StructureLostArmor'), (505, 'StructureLostShields'), (506, 'StructureOnline'), (507, 'StructureServicesOffline'), (508, 'StructureUnanchoring'), (509, 'StructureUnderAttack'), (510, 'StructureWentHighPower'), (511, 'StructureWentLowPower'), (601, 'OrbitalAttacked'), (602, 'OrbitalReinforced'), (701, 'TowerAlertMsg'), (702, 'TowerResourceAlertMsg'), (801, 'EntosisCaptureStarted'), (802, 'SovCommandNodeEventStarted'), (803, 'SovAllClaimAquiredMsg'), (804, 'SovStructureReinforced'), (805, 'SovStructureDestroyed')], default=structures.models.get_default_notification_types, help_text='only notifications which selected types are sent to this webhook', max_length=103),
        ),
    ]
