# Generated by Django 2.2.11 on 2020-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0009_localizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EveSovereigntyMap',
            fields=[
                ('solar_system_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('alliance_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='alliance who holds sov for this system', null=True)),
                ('corporation_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='corporation who holds sov for this system', null=True)),
                ('faction_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='faction who holds sov for this system', null=True)),
                ('last_updated', models.DateTimeField(blank=True, db_index=True, default=None, help_text='When this object was last updated from ESI', null=True)),
            ],
        ),
    ]
