# Generated by Django 2.2.5 on 2019-11-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0009_auto_20191118_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='character',
            field=models.ForeignKey(blank=True, default=None, help_text='character used for syncing structures', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.CharacterOwnership'),
        ),
    ]
