# Generated by Django 3.1.6 on 2021-02-16 01:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0017_war_dec_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="notification_types",
        ),
        migrations.AddField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="type of this notification as reported by ESI",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="notification_groups",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (10, "Corporation Member"),
                    (20, "Moon Mining"),
                    (30, "Upwell Structure"),
                    (40, "Customs Office"),
                    (50, "Starbase"),
                    (60, "Sovereignty"),
                    (70, "War"),
                ],
                default="",
                help_text="only notifications which selected types are sent to this webhook",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created",
            field=models.DateTimeField(
                default=None,
                help_text="Date when this notification was first received from ESI",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                default=None,
                help_text="True when this notification has read in the eve client",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_sent",
            field=models.BooleanField(
                default=False,
                help_text="True when this notification has been forwarded to Discord",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_timer_added",
            field=models.BooleanField(
                default=None,
                help_text="True when a timer has been added for this notification",
                null=True,
            ),
        ),
    ]
