# Generated by Django 3.1.6 on 2021-02-16 02:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0018_refactor_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="type of this notification as reported by ESI",
                max_length=100,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="notification_groups",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (10, "Corporation Member"),
                    (20, "Moon Mining"),
                    (30, "Upwell Structure"),
                    (40, "Customs Office"),
                    (50, "Starbase"),
                    (60, "Sovereignty"),
                    (70, "War"),
                ],
                default="",
                help_text="only notifications from selected groups are sent to this webhook",
                max_length=20,
            ),
        ),
    ]
