# Generated by Django 3.1.6 on 2021-02-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0019_auto_20210216_0251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_id",
            field=models.PositiveBigIntegerField(verbose_name="id"),
        ),
    ]
