# Generated by Django 3.1.6 on 2021-02-18 15:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0019_auto_20210217_2244"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="notification_types",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("CharAppAcceptMsg", "Char App Accept Msg"),
                    ("CharLeftCorpMsg", "Char Left Corp Msg"),
                    ("MoonminingAutomaticFracture", "Moonmining Automatic Fracture"),
                    (
                        "MoonminingExtractionCancelled",
                        "Moonmining Extraction Cancelled",
                    ),
                    ("MoonminingExtractionFinished", "Moonmining Extraction Finished"),
                    ("MoonminingExtractionStarted", "Moonmining Extraction Started"),
                    ("MoonminingLaserFired", "Moonmining Laser Fired"),
                    ("StructureAnchoring", "Structure Anchoring"),
                    ("StructureDestroyed", "Structure Destroyed"),
                    ("StructureFuelAlert", "Structure Fuel Alert"),
                    ("StructureLostArmor", "Structure Lost Armor"),
                    ("StructureLostShields", "Structure Lost Shield"),
                    ("StructureOnline", "Structure Online"),
                    ("StructureServicesOffline", "Structure Services Offline"),
                    ("StructureUnanchoring", "Structure Unanchoring"),
                    ("StructureUnderAttack", "Structure Under Attack"),
                    ("StructureWentHighPower", "Structure Went High Power"),
                    ("StructureWentLowPower", "Structure Went Low Power"),
                    ("OwnershipTransferred", "Ownership Transferred"),
                    ("OrbitalAttacked", "Orbital Attacked"),
                    ("OrbitalReinforced", "Orbital Reinforced"),
                    ("TowerAlertMsg", "Tower Alert Msg"),
                    ("TowerResourceAlertMsg", "Tower Resource Alert Msg"),
                    ("EntosisCaptureStarted", "Sov Entosis Capture Started"),
                    ("SovCommandNodeEventStarted", "Sov Command Node Event Started"),
                    ("SovAllClaimAquiredMsg", "Sov All Claim Acquired Msg"),
                    ("SovStructureReinforced", "Sov Structure Reinforced"),
                    ("SovStructureDestroyed", "Sov Structure Destroyed"),
                    ("AllyJoinedWarAggressorMsg", "War Ally Joined War Aggressor Msg"),
                    ("CorpWarSurrenderMsg", "War Corp War Surrender Msg"),
                    ("WarAdopted", "War War Adopted"),
                    ("WarDeclared", "War War Declared"),
                    ("WarInherited", "War War Inherited"),
                    ("WarRetractedByConcord", "War War Retracted By Concord"),
                ],
                default="",
                max_length=704,
            ),
        ),
    ]
