# Generated by Django 3.1.2 on 2021-02-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0020_more_war_notifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    (
                        "basic_access",
                        "Can access this app and view structures of your corporation",
                    ),
                    ("view_alliance_structures", "Can view alliance structures"),
                    ("view_all_structures", "Can view all structures"),
                    ("add_structure_owner", "Can add new structure owner"),
                    (
                        "view_all_unanchoring_status",
                        "Can view unanchoring timers for all structures the user can see",
                    ),
                    ("view_structure_fit", "Can view structure fit"),
                ),
            },
        ),
        migrations.AddField(
            model_name="owner",
            name="assets_last_error",
            field=models.IntegerField(
                choices=[
                    (0, "No error"),
                    (1, "Invalid token"),
                    (2, "Expired token"),
                    (3, "Insufficient permissions"),
                    (4, "No character set for fetching data from ESI"),
                    (5, "ESI API is currently unavailable"),
                    (6, "Operaton mode does not match with current setting"),
                    (99, "Unknown error"),
                ],
                default=0,
                help_text="error that occurred at the last sync atttempt (if any)",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="assets_last_sync",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="when the last sync happened",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="structure",
            name="has_fit",
            field=models.BooleanField(
                default=False, help_text="bool indicating if the structure has a fit"
            ),
        ),
        migrations.CreateModel(
            name="OwnerAsset",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="The Item ID of the assets",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_singleton", models.BooleanField()),
                ("location_flag", models.CharField(max_length=255)),
                ("location_id", models.BigIntegerField()),
                ("location_type", models.CharField(max_length=255)),
                ("quantity", models.IntegerField()),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "eve_type",
                    models.ForeignKey(
                        help_text="type of the assets",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structures.evetype",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Corporation that owns the assets",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="structures.owner",
                    ),
                ),
            ],
        ),
    ]
