# Generated by Django 3.1.6 on 2021-02-16 12:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0021_auto_20210216_1202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="notification_groups",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("CM", "Corporation Member"),
                    ("MM", "Moon Mining"),
                    ("US", "Upwell Structure"),
                    ("CO", "Customs Office"),
                    ("SB", "Starbase"),
                    ("SV", "Sovereignty"),
                    ("WR", "War"),
                ],
                default=None,
                help_text="only notifications from selected groups are sent to this webhook",
                max_length=20,
            ),
        ),
    ]
