# Generated by Django 3.1.6 on 2021-02-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0021_auto_20210218_1744"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhook",
            name="disabled_notification_types",
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_timer_added",
            field=models.BooleanField(
                default=False,
                help_text="True when a timer has been added for this notification",
                null=True,
            ),
        ),
    ]
