# Generated by Django 3.1.6 on 2021-02-16 13:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0022_auto_20210216_1255"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="disabled_notification_types",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("CharAppAcceptMsg", "CharAppAcceptMsg"),
                    ("CharLeftCorpMsg", "CharLeftCorpMsg"),
                    ("MoonminingAutomaticFracture", "MoonminingAutomaticFracture"),
                    ("MoonminingExtractionCancelled", "MoonminingExtractionCancelled"),
                    ("MoonminingExtractionFinished", "MoonminingExtractionFinished"),
                    ("MoonminingExtractionStarted", "MoonminingExtractionStarted"),
                    ("MoonminingLaserFired", "MoonminingLaserFired"),
                    ("StructureAnchoring", "StructureAnchoring"),
                    ("StructureDestroyed", "StructureDestroyed"),
                    ("StructureFuelAlert", "StructureFuelAlert"),
                    ("StructureLostArmor", "StructureLostArmor"),
                    ("StructureLostShields", "StructureLostShields"),
                    ("StructureOnline", "StructureOnline"),
                    ("StructureServicesOffline", "StructureServicesOffline"),
                    ("StructureUnanchoring", "StructureUnanchoring"),
                    ("StructureUnderAttack", "StructureUnderAttack"),
                    ("StructureWentHighPower", "StructureWentHighPower"),
                    ("StructureWentLowPower", "StructureWentLowPower"),
                    ("OwnershipTransferred", "OwnershipTransferred"),
                    ("OrbitalAttacked", "OrbitalAttacked"),
                    ("OrbitalReinforced", "OrbitalReinforced"),
                    ("TowerAlertMsg", "TowerAlertMsg"),
                    ("TowerResourceAlertMsg", "TowerResourceAlertMsg"),
                    ("EntosisCaptureStarted", "EntosisCaptureStarted"),
                    ("SovCommandNodeEventStarted", "SovCommandNodeEventStarted"),
                    ("SovAllClaimAquiredMsg", "SovAllClaimAquiredMsg"),
                    ("SovStructureReinforced", "SovStructureReinforced"),
                    ("SovStructureDestroyed", "SovStructureDestroyed"),
                    ("AllyJoinedWarAggressorMsg", "AllyJoinedWarAggressorMsg"),
                    ("CorpWarSurrenderMsg", "CorpWarSurrenderMsg"),
                    ("WarAdopted", "WarAdopted"),
                    ("WarDeclared", "WarDeclared"),
                    ("WarInherited", "WarInherited"),
                    ("WarRetractedByConcord", "WarRetractedByConcord"),
                ],
                default=None,
                help_text="Disables sending of notifications for selected notification types (regardless of selected notification groups)",
                max_length=704,
            ),
        ),
    ]
