# Generated by Django 3.1.6 on 2021-04-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0025_auto_20210429_1216"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="has_fit",
        ),
        migrations.AddField(
            model_name="structure",
            name="has_fitting",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="bool indicating if the structure has a fitting",
                null=True,
            ),
        ),
    ]
