# Generated by Django 3.1.10 on 2021-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0025_poco_feature_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pocodetails",
            name="standing_level",
            field=models.IntegerField(
                choices=[
                    (-99, "none"),
                    (-10, "terrible"),
                    (-5, "bad"),
                    (0, "neutral"),
                    (5, "good"),
                    (10, "excellent"),
                ],
                default=-99,
            ),
        ),
    ]
