# Generated by Django 3.1.12 on 2021-07-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0026_rework_update_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="owner",
            old_name="character",
            new_name="character_ownership",
        ),
    ]
