# Generated by Django 3.1.6 on 2021-04-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0026_auto_20210429_2131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="has_core",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=None,
                help_text="bool indicating if the structure has a quantum core",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="has_fitting",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=None,
                help_text="bool indicating if the structure has a fitting",
                null=True,
            ),
        ),
    ]
