# Generated by Django 3.1.12 on 2021-07-16 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("structures", "0028_migrate_owner_characters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="ping_groups",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Groups to be pinged for each notification - ",
                related_name="_webhook_ping_groups_+",
                to="auth.Group",
            ),
        ),
        migrations.CreateModel(
            name="FuelNotificationConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_ping_type",
                    models.CharField(
                        choices=[
                            ("PN", "(none)"),
                            ("PH", "@here"),
                            ("PE", "@everybody"),
                        ],
                        default="PH",
                        help_text="Option to ping every member of the channel",
                        max_length=2,
                        verbose_name="channel pings",
                    ),
                ),
                (
                    "category",
                    models.PositiveIntegerField(
                        choices=[(65, "Structure"), (23, "Starbase")]
                    ),
                ),
                (
                    "end",
                    models.PositiveIntegerField(
                        help_text="End of alerts in hours before fuel expires"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        help_text="Frequency of alerts in hours"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("default", "default"),
                            ("primary", "primary"),
                            ("success", "success"),
                            ("info", "info"),
                            ("warning", "warning"),
                            ("danger", "danger"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "start",
                    models.PositiveIntegerField(
                        help_text="Start of alerts in hours before fuel expires"
                    ),
                ),
                (
                    "webhooks",
                    models.ManyToManyField(
                        related_name="fuel_alert_configs", to="structures.Webhook"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuelNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        help_text="number of hours before fuel expiration this alert was sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_alerts_sent",
                        to="structures.fuelnotificationconfig",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_alerts_sent",
                        to="structures.structure",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
