# Generated by Django 3.1.12 on 2021-07-16 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("structures", "0028_migrate_owner_characters"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelAlertConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_ping_type",
                    models.CharField(
                        choices=[
                            ("PN", "(none)"),
                            ("PH", "@here"),
                            ("PE", "@everybody"),
                        ],
                        default="PH",
                        help_text="Option to ping every member of the channel",
                        max_length=2,
                        verbose_name="channel pings",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("ST", "Structure"), ("SB", "starbase")], max_length=2
                    ),
                ),
                (
                    "end",
                    models.PositiveIntegerField(
                        help_text="End of alerts in hours before fuel expires"
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        help_text="Frequency of alerts in hours"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "start",
                    models.PositiveIntegerField(
                        help_text="Start of alerts in hours before fuel expires"
                    ),
                ),
                (
                    "ping_groups",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="Groups to be pinged for each alert - ",
                        related_name="_fuelalertconfig_ping_groups_+",
                        to="auth.Group",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="webhook",
            name="ping_groups",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Groups to be pinged for each notification - ",
                related_name="_webhook_ping_groups_+",
                to="auth.Group",
            ),
        ),
        migrations.CreateModel(
            name="FuelAlertSend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        help_text="number of hours before fuel expiration this alert was sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_alerts_sent",
                        to="structures.fuelalertconfig",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_alerts_sent",
                        to="structures.owner",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_alerts_sent",
                        to="structures.structure",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fuelalertconfig",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="structures.webhook"
            ),
        ),
    ]
