# Generated by Django 3.1.12 on 2021-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0029_auto_20210716_1328"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelalertconfig",
            name="webhook",
        ),
        migrations.AddField(
            model_name="fuelalertconfig",
            name="webhooks",
            field=models.ManyToManyField(
                related_name="fuel_alert_configs", to="structures.Webhook"
            ),
        ),
        migrations.AlterField(
            model_name="fuelalertconfig",
            name="category",
            field=models.CharField(
                choices=[("ST", "Structure"), ("SB", "Starbase")], max_length=2
            ),
        ),
    ]
