# Generated by Django 3.1.13 on 2021-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0029_add_fuel_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ownercharacter",
            name="last_used_at",
        ),
        migrations.AddField(
            model_name="ownercharacter",
            name="notifications_last_used_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                editable=False,
                help_text="when this character was last used for syncing notifications",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ownercharacter",
            name="structures_last_used_at",
            field=models.DateTimeField(
                db_index=True,
                default=None,
                editable=False,
                help_text="when this character was last used for syncing structures",
                null=True,
            ),
        ),
    ]
