# Generated by Django 3.1.12 on 2021-07-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0030_auto_20210716_1851"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelnotificationconfig",
            name="webhooks",
        ),
    ]
