# Generated by Django 3.1.13 on 2021-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0030_update_refueled_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="is_up",
            field=models.BooleanField(
                default=True,
                help_text="whether all services for this owner are currently up",
            ),
        ),
    ]
