# Generated by Django 3.1.13 on 2021-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0031_owner_is_up"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="assets_last_update_ok",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="forwarding_last_update_ok",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="notifications_last_update_ok",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="structures_last_update_ok",
        ),
        migrations.AlterField(
            model_name="owner",
            name="assets_last_update_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="when the last successful update happened",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="forwarding_last_update_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="when the last successful update happened",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="notifications_last_update_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="when the last successful update happened",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="structures_last_update_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="when the last successful update happened",
                null=True,
            ),
        ),
    ]
