# Generated by Django 3.1.13 on 2021-09-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0031_owner_is_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="is_up",
            field=models.BooleanField(
                default=None,
                editable=False,
                help_text="whether all services for this owner are currently up",
                null=True,
            ),
        ),
    ]
