# Generated by Django 3.1.12 on 2021-07-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0031_remove_fuelnotificationconfig_webhooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelnotificationconfig",
            name="category",
        ),
    ]
