# Generated by Django 3.1.12 on 2021-07-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0032_remove_fuelnotificationconfig_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelnotification",
            name="config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_notifications",
                to="structures.fuelnotificationconfig",
            ),
        ),
        migrations.AlterField(
            model_name="fuelnotification",
            name="structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_notifications",
                to="structures.structure",
            ),
        ),
    ]
