# Generated by Django 3.2.9 on 2021-12-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0032_rename_fuelalert_structurefuelalert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FuelAlertConfig',
            new_name='StructureFuelAlertConfig',
        ),
    ]
