# Generated by Django 3.2.9 on 2021-12-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0033_alter_webhook_notification_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructureItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="The Eve item ID", primary_key=True, serialize=False
                    ),
                ),
                ("is_singleton", models.BooleanField()),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
                ("location_flag", models.CharField(max_length=255)),
                ("location_id", models.BigIntegerField(db_index=True)),
                ("quantity", models.IntegerField()),
                (
                    "eve_type",
                    models.ForeignKey(
                        help_text="eve type of the item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="structures.evetype",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        help_text="Structure this item is located in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="structures.structure",
                    ),
                ),
            ],
        ),
    ]
