# Generated by Django 3.2.11 on 2022-01-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0033_add_structure_webhooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="structure",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Structure this notification is about (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="notifications",
                to="structures.structure",
            ),
        ),
    ]
