# Generated by Django 3.2.9 on 2021-12-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0033_rename_fuelalertconfig_structurefuelalertconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpFuelAlertConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_ping_type', models.CharField(choices=[('NO', 'none'), ('HE', 'here'), ('EV', 'everyone')], default='HE', help_text='Option to ping every member of the channel. This setting can be overruled by the respective owner or webhook configuration', max_length=2, verbose_name='channel pings')),
                ('color', models.IntegerField(blank=True, choices=[(14242639, 'danger'), (6013150, 'info'), (6076508, 'success'), (15773006, 'warning')], default=15773006, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('threshold', models.PositiveIntegerField(help_text='Notifications will be sent once fuel level in units reaches this threshold')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
