# Generated by Django 3.2.9 on 2021-12-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0034_jumpfuelalertconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefuelalert',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_fuel_alerts', to='structures.structurefuelalertconfig'),
        ),
        migrations.AlterField(
            model_name='structurefuelalert',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_fuel_alerts', to='structures.structure'),
        ),
    ]
