# Generated by Django 3.2.11 on 2022-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0034_add_structure_webhooks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structure",
            name="webhooks",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Webhooks for sending notifications to. If any webhook is enabled, these will be used instead of the webhooks defined for the respective owner. If no webhook is enabled the owner's setting will be used. ",
                related_name="structures",
                to="structures.Webhook",
            ),
        ),
    ]
