# Generated by Django 3.2.9 on 2021-12-12 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0034_structureitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structureitem",
            name="structure",
            field=models.ForeignKey(
                help_text="Structure this item is located in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="structures.structure",
            ),
        ),
    ]
