# Generated by Django 3.1.12 on 2021-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0034_auto_20210719_1229"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelnotificationconfig",
            name="level",
        ),
        migrations.AddField(
            model_name="fuelnotificationconfig",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    (14242639, "danger"),
                    (6013150, "info"),
                    (6076508, "success"),
                    (15773006, "warning"),
                ],
                default=6013150,
                max_length=10,
                null=True,
            ),
        ),
    ]
