# Generated by Django 3.2.9 on 2021-12-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0035_alter_structureitem_structure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structureitem",
            name="location_id",
        ),
    ]
