# Generated by Django 3.2.9 on 2021-12-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0036_remove_structureitem_location_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OwnerAsset",
        ),
    ]
