# Generated by Django 3.1.12 on 2021-07-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0038_auto_20210719_1413"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelnotification",
            name="hours",
            field=models.PositiveIntegerField(
                db_index=True,
                help_text="number of hours before fuel expiration this alert was sent",
            ),
        ),
    ]
