# Generated by Django 4.0.3 on 2022-05-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0038_add_starbase_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starbasedetail",
            name="structure",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="starbase_detail",
                to="structures.structure",
            ),
        ),
    ]
