# Generated by Django 3.1.12 on 2021-07-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0039_auto_20210719_1416"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fuelnotificationconfig",
            old_name="frequency",
            new_name="repeat",
        ),
    ]
