# Generated by Django 4.0.7 on 2022-08-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0040_alter_webhook_notification_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuresnotification",
            name="is_timer_added",
            field=models.BooleanField(
                default=False,
                help_text="True when a timer has been added for this notification",
            ),
        ),
    ]
