# Generated by Django 4.0.7 on 2022-08-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0040_alter_notification_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatednotification",
            name="structures",
            field=models.ManyToManyField(
                help_text="Structures this notification is about (if any)",
                related_name="generated_notifications",
                to="structures.structure",
            ),
        ),
    ]
