# Generated by Django 3.1.12 on 2021-07-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0040_auto_20210719_1815"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fuelnotificationconfig",
            name="repeat",
            field=models.PositiveIntegerField(
                help_text="Notifications will be repeated every x hours. Set to 0 for no repeats"
            ),
        ),
    ]
