# Generated by Django 4.0.7 on 2022-08-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0041_generatednotification_structures"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatednotification",
            name="is_timer_added",
            field=models.BooleanField(
                default=False,
                help_text="True when a timer has been added for this notification",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="generatednotification",
            name="notif_type",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="type of this notification",
                max_length=100,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="generatednotification",
            name="structures",
            field=models.ManyToManyField(
                help_text="Structures this notification is about (if any)",
                to="structures.structure",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="type of this notification",
                max_length=100,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="structures",
            field=models.ManyToManyField(
                help_text="Structures this notification is about (if any)",
                to="structures.structure",
            ),
        ),
    ]
