# Generated by Django 4.0.7 on 2022-08-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0042_alter_generatednotification_is_timer_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatednotification",
            name="owner",
            field=models.ForeignKey(
                help_text="Corporation that owns this notification",
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.owner",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="owner",
            field=models.ForeignKey(
                help_text="Corporation that owns this notification",
                on_delete=django.db.models.deletion.CASCADE,
                to="structures.owner",
            ),
        ),
    ]
