# Generated by Django 4.0.7 on 2022-08-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0043_remove_generatednotification_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generatednotification",
            old_name="created",
            new_name="timestamp",
        ),
    ]
