# Generated by Django 4.0.7 on 2022-08-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("structures", "0044_rename_created_generatednotification_timestamp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "eve notification"},
        ),
    ]
